version: '3.8'

services:

  postgres:
    image: postgres:18

    container_name: postgres-db

    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <password>

    ports:
      - "5432:5432"

  app:

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: <password>

    build: .

    container_name: finance-tracker

    ports:
      - "8080:8080"

    depends_on:
      - postgres